version: '2'
services:
  # api:
  #   build: ./api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     DB_HOST: "TEST"
  #     PORT: 3001

  # palindrome-service:
  #   build: ./palindrome-service
  #   environment:
  #     DB_HOST: "TEST"
  
  # redis:
  #   image: "redis:5"
  #   ports:
  #     - "6379:6379"

  db:
    image: "mongo:4.2.0-bionic"
    ports:
      - "27017:27017"    
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
