version: '2'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    links:
      - mongodb
      - redis
    environment:
      DB_HOST: "mongodb"
      REDIS_HOST: "redis"
      PORT: 3000
    depends_on:
      - redis

  palindrome-service:
    build: ./palindrome-service
    links:
      - mongodb
      - redis
    environment:
      DB_HOST: "mongodb"
      REDIS_HOST: "redis"
    depends_on:
      - redis
  
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:4.2.0-bionic"
    ports:
      - "27017:27017"    
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
