version: '2'
services:
  # api:
  #   build: ./api
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     DB_HOST: "TEST"

  # rabbitmq:
  #   image: "rabbitmq:3-management"
  #   hostname: "rabbitmq"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "rabbitmq"
  #     RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   labels:
  #     NAME: "rabbitmq"
  #   volumes:
  #     - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
  
  redis:
    image: "redis:5"
    ports:
      - "6379:6379"

  db:
    image: "mongo:4.2.0-bionic"
    ports:
      - "27017:27017"    
    volumes:
      - data-volume:/data/db

volumes:
  data-volume:
